name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Copy .env
        run: |
          cp .env.example .env
          sed -i 's/NODE_ENV=local/NODE_ENV=${{ secrets.NODE_ENV }}/g' .env
          sed -i 's|VUE_APP_API_BASE_URL=https://websitein.id/|VUE_APP_API_BASE_URL=${{ secrets.VUE_APP_API_BASE_URL }}|g' .env
          sed -i 's|VUE_APP_NAME=Kasirin|VUE_APP_NAME=${{ secrets.VUE_APP_NAME }}|g' .env
          sed -i 's/REVERB_APP_ID=app-id/REVERB_APP_ID=${{ secrets.REVERB_APP_ID }}/g' .env
          sed -i 's/REVERB_APP_KEY=app-key/REVERB_APP_KEY=${{ secrets.REVERB_APP_KEY }}/g' .env
          sed -i 's/REVERB_APP_SECRET=app-secret/REVERB_APP_SECRET=${{ secrets.REVERB_APP_SECRET }}/g' .env
          sed -i 's/REVERB_HOST=websitein.id/REVERB_HOST=${{ secrets.REVERB_HOST }}/g' .env
          sed -i 's/REVERB_PORT=443/REVERB_PORT=${{ secrets.REVERB_PORT }}/g' .env
          sed -i 's/REVERB_SCHEME=https/REVERB_SCHEME=${{ secrets.REVERB_SCHEME }}/g' .env

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PROD_SERVER }}
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: './dist/'
          server-dir: './'